### ISSUE TITLE
Instagram has changed the url of the images posted on his platform 😒

### ISSUE THREAD

**Issue by SunSea88** [TalkLounge/instagram-fix-image-linking#1]
Hello again,

This is just to let you know that Instagram has changed the url of the images posted on any Account again 😔
-> https://www.instagram.com/p/* has become https://www.instagram.com/Account Name/p/*

That's why the right click on the images doesn't work anymore.

**Comment by TalkLounge** [comment]
Thanks for reporting. Fixed

**Comment by SunSea88** [comment]
No problem and Thank you very much, it's really much better now 😄
